/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package snake;

import snake.interfaces.Incrementer1;

/**
 *
 * @author margargar96
 */
public class Scoreboard extends javax.swing.JPanel implements Incrementer1 {

    private String name1 = "Player 1";
    private String name2 = "Player 2";
    private int score1 = 0;
    private int score2 = 0;
    private boolean isMultijugador = false;

    public Scoreboard() {
        initComponents();
        updateLabels();
    }

    public void setMultijugador(boolean multi) {
        this.isMultijugador = multi;
        updateLabels();
    }

    private void updateLabels() {
        if (jLabel1 == null) {
            return; 
        }
        jLabel1.setText(name1 + ": " + score1);

        if (isMultijugador) {
            jLabel2.setText(name2 + ": " + score2);
            jLabel2.setVisible(true); 
        } else {
            jLabel2.setText(""); 
            jLabel2.setVisible(false); 
        }
    }

    public void setPlayerName(String name) {
        this.name1 = name;
        updateLabels();
    }

    public void setPlayer2Name(String name) {
        this.name2 = name;
        updateLabels();
    }

    @Override
    public void incrementScore(int player, int amount) {
        if (player == 1) {
            score1 += amount;
        } else {
            score2 += amount;
        }
        updateLabels();
    }

    @Override
    public void reset() {
        score1 = 0;
        score2 = 0;
        updateLabels();
    }

    /**
     * Creates new form Scoreboard
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Gayathri", 0, 18)); // NOI18N
        jLabel1.setText("               jLabel1");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setFont(new java.awt.Font("Gayathri", 0, 18)); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
